// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs7nro0EkYtkED-2hkAwISZBJAdmB3cPQ',
    appId: '1:381982050670:web:78850620cd185558bd997f',
    messagingSenderId: '381982050670',
    projectId: 'ecommerce-app-51cc9',
    authDomain: 'ecommerce-app-51cc9.firebaseapp.com',
    storageBucket: 'ecommerce-app-51cc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSz7XFdrjHjvO22mcLuxjrxxlp07thhFw',
    appId: '1:381982050670:android:0c74a8c9ad555de9bd997f',
    messagingSenderId: '381982050670',
    projectId: 'ecommerce-app-51cc9',
    storageBucket: 'ecommerce-app-51cc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzpEUxgMg6m5L0-VBw4Zjr03LK4qn1VDk',
    appId: '1:381982050670:ios:8657765b201b491ebd997f',
    messagingSenderId: '381982050670',
    projectId: 'ecommerce-app-51cc9',
    storageBucket: 'ecommerce-app-51cc9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
